[package]
name = "cargo-scout-macros"
version = "0.1.0"
authors = ["yonip23 <yoni@codota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
