language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - RUST_BACKTRACE=1
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D clippy::pedantic
  - cargo test --all
