language: rust
rust:
  - stable
  - nightly
sudo: required
matrix:
  allow_failures:
    - rust: nightly
env:
  - RUST_BACKTRACE=1
addons:
  apt:
    packages:
      - libssl-dev
before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      cargo install cargo-tarpaulin -f
      rustup component add clippy
    fi
  - rustup component add rustfmt
script:
  - cargo fmt -- --check
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      cargo clippy -- -D clippy::pedantic
      USE_SKEPTIC=1 cargo tarpaulin --out Xml
      bash <(curl -s https://codecov.io/bash)
      echo "Uploaded code coverage"
    fi
  - cargo test --all
